while True:
    
    try:
        import sys
        import time
        import sqlite3
        import smtplib
        import re
        from colorama import init
        init(strip=not sys.stdout.isatty()) # strip colors if stdout is redirected
        from termcolor import cprint 
        from pyfiglet import figlet_format

    except ImportError:
        print("ALL MODULES NOT INSTALLED")
        
    tech = cprint(figlet_format('TECHSHOW', font='slant'),
           'yellow', 'on_red', attrs=['bold'])
    feed = cprint(figlet_format('FEEDBACK', font='slant'),
           'yellow', 'on_red', attrs=['bold'])
    retr = cprint(figlet_format('RETRIEVER', font='slant'),
           'yellow', 'on_red', attrs=['bold'])
   

    result = cprint(figlet_format("MADE BY PRATHAM AGARWAL", font = "digital" ),'yellow', 'on_red' , attrs=['bold']) 


    

    db = sqlite3.connect("review.db")
    print(figlet_format("ENTER YOUR NAME : ",font ='digital'))
    name = str(input(""))
    y = True
    while y:
        try:
            print(figlet_format("ENTER YOUR GRADE",font ='digital'))
            grade = int(input(""))
            y = False
        except ValueError:
            print("THATS NOT A NUMBER. RE-ENTER YOUR GRADE")
            continue
    z = True
    while z:
        try:
            print(figlet_format("ENTER YOUR ENROLLMENT NUMBER",font ='digital'))
            enrollment_no = int(input(""))
            z = False
        except ValueError:
            print("THATS NOT A NUMBER ENROLLEMENT NUMBERS ARE LIKE 2013040312 ")
            print("RE-ENTER")
            continue
    x = True
    while x:
        print(figlet_format("ENTER YOUR EMAIL",font ='digital'))
        email_id = str(input(""))
        pattern = r'@'
        if re.search(pattern,email_id):
            x = False
        else:
            print("THATS NO THE CORRECT EMAIL ID")
            print("EMAIL IDs ARE OF FORM abc@xyz.com \n PLEASE RE-ENTER THE EMAIL ID .")
            continue


    while True:
        try:
            rating = int(input("ON THE SCALE FROM 1 TO 10 . \n HOW WOULD YOU LIKE TO RATE THE TECHSHOW ? "))
        except ValueError:
            print("THATS NOT A NUMBER . I ACCEPT ONLY NUMBERS BETWEEN 1-10 ")
            continue

        

        if  rating > 11 and rating > 0:
            

            print("Oops Please give it on the scale of 1-10")
            continue
        else:
            print("Thank you for your valuable feedback")
            break
    print(figlet_format("ENTER YOUR SUGGESTIONS : ",font ='digital'))
    print("Type NA if no suggestions ")
    suggestions = str(input(""))
    
    
    content = '''Thank You parents of {0} of class {1}th for rating us {2} out of 10 on our FEEDBACK-RETRIEVER-APP. \nThis is an autogenerated-email from our servers. \nThank You for visiting the Tech-show hosted at Delhi Public School ,Rajnagar.\n \nLog on to www.dps.ind.in for more such content in future \n \n \nRegards '''.format(name,grade,rating)  
    
    server = smtplib.SMTP('smtp.gmail.com',587)
    server.starttls()
    server.login('agarwalpratham1812@gmail.com','clasherrox@lways')
    server.sendmail('agarwalpratham1812@gmail.com',email_id,content)

    print("PLEASE CHECK YOUR EMAIL \n ;- ) ")
    db.execute("CREATE TABLE IF NOT EXISTS review(student_name TEXT,grade INTEGER,email TEXT,review INTEGER,suggestions TEXT)")
    db.execute("INSERT INTO review(student_name,grade,email,review,suggestions) VALUES(?,?,?,?,?)",(name,grade,email_id,rating,suggestions))
    update_cursor = db.cursor()
    print("{0} RESPONSES HAVE BEEN RECORDED ".format(update_cursor.rowcount))
    update_cursor.close()
    db.commit()
    db.close()
    time.sleep(5)
    continue

    
